[[stack]]
name = "autoimmune_disease_prediction"

[stack.config]
server = "vh3"
project_name = "autoimmune_disease_prediction"
auto_update = true
auto_update_all_services = true
repo = "noraidouaouzal-etu-lab/autoimmune-mlops"
reclone = false
file_paths = [
  "deploy/docker-compose.production.yml"
]
environment = """
DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
"""