services:
  dagster:
    image: ${DOCKERHUB_USERNAME}/autoimmune-dagster:latest
    container_name: autoimmune_disease_prediction-dagster
    ports:
      - "4001:3000"
    volumes:
      - autoimmune_disease_prediction-shared_pipeline_data:/app/data
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000", "-f", "orchestration.py"]

  backend:
    image: ${DOCKERHUB_USERNAME}/autoimmune-backend:latest
    container_name: autoimmune_disease_prediction-backend
    ports:
      - "4002:8000"
    environment:
      - DUCKDB_PATH=/app/data/duckdb/fsbm.duckdb
    volumes:
      - autoimmune_disease_prediction-shared_pipeline_data:/app/data
    depends_on:
      - dagster

  frontend:
    image: ${DOCKERHUB_USERNAME}/autoimmune-frontend:latest
    container_name: autoimmune_disease_prediction-frontend
    ports:
      - "4003:8501"
    environment:
    - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  monitoring:
    image: ${DOCKERHUB_USERNAME}/autoimmune-monitoring:latest
    container_name: autoimmune_disease_prediction-monitoring
    volumes:
      - autoimmune_disease_prediction-logs:/app/monitoring/logs
      - autoimmune_disease_prediction-reports:/app/monitoring/reports
      - autoimmune_disease_prediction-shared_pipeline_data:/app/data
    depends_on:
      - backend
    restart: unless-stopped
    
  dashboard:
    image: ${DOCKERHUB_USERNAME}/autoimmune-dashboard:latest
    container_name: autoimmune_disease_prediction-dashboard
    ports:
      - "4004:8501"
    environment:
      - BACKEND_URL=http://ml-backend:8000
    volumes:
      - autoimmune_disease_prediction-logs:/app/monitoring/logs
      - autoimmune_disease_prediction-reports:/app/monitoring/reports
    depends_on:
      - backend

volumes:
  duckdb_volume:
  autoimmune_disease_prediction-logs:
  autoimmune_disease_prediction-reports:
  autoimmune_disease_prediction-shared_pipeline_data:
