FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip
RUN pip install streamlit pandas requests

COPY . .
ENV PYTHONPATH=/app

EXPOSE 8501

CMD ["streamlit", "run", "monitoring/dashboard/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]